steps:
# Build container image 
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/andres-testing/nginx:latest', '.' ]
# Push container image to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/andres-testing/nginx:latest']

#  Copy the container image to gcr - it also shows the image in the build resutls at the build logs
#images:
#- 'gcr.io/caylent-testing/nginx:1.0.2'

#decrypts the alz-sa service account key from repo
#- name: gcr.io/cloud-builders/gcloud
#  args:
#  - kms
#  - decrypt
#  - --ciphertext-file=alz-sa-key.json.enc
#  - --plaintext-file=alz-sa-key.json
#  - --location=us-east1
#  - --keyring=caylent-testing-key-ring
#  - --key=caylent-testing-key
#  - --project=caylent-testing

  # testing my builder
- name: "gcr.io/andres-testing/mybuilder"
  args: ['/bin/bash', 'script.sh']

# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=resource.yml
  - --location=us-west1-1
  - --cluster=gke-e2e-demo