--- 
steps: 
  - 
    args: 
      - build
      - "-t"
      - "gcr.io/andres-testing/nginx:latest"
      - "."
    name: gcr.io/cloud-builders/docker
  - 
    args: 
      - push
      - "gcr.io/andres-testing/nginx:latest"
    name: gcr.io/cloud-builders/docker
  - 
    args: 
      - "-c"
      - |
          PROJECT_ID=$(gcloud config get-value project)
          gcloud container clusters get-credentials gke-e2e-demo --zone us-west1-a --project $PROJECT_ID
          echo y | gcloud compute ssh instance-1 --project $PROJECT_ID --zone us-west1-a --  -L 8888:localhost:8888 -N -q -f
          export HTTPS_PROXY=localhost:8888
          kubectl get nodes
          kubectl apply -f resources.yaml
    entrypoint: bash
    id: delete_deployment
    name: gcr.io/cloud-builders/gke-deploy
  - 
    args: 
      - "-c"
      - |
          PROJECT_ID=$(gcloud config get-value project)
          gcloud container clusters get-credentials gke-e2e-demo --zone us-west1-a --project $PROJECT_ID
          echo y | gcloud compute ssh instance-1 --project $PROJECT_ID --zone us-west1-a --  -L 8888:localhost:8888 -N -q -f
          export HTTPS_PROXY=localhost:8888
          kubectl delete -f resources.yaml
    entrypoint: bash
    id: delete_deployment
    name: gcr.io/cloud-builders/gke-deploy
