steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/caylent-testing/nginx:1.0.3', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/caylent-testing/nginx:1.0.3']
#  The lines below would build, push, but also show the image in the build resutls at the biuld logs
#images:
#- 'gcr.io/caylent-testing/nginx:1.0.2'
