steps:

## Build container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/andres-testing/nginx:latest', '.' ]

## Push container image to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/andres-testing/nginx:latest']

## Getting the node public IP.
#- id: whitelist
#  name: "gcr.io/andres-testing/mybuilder:0.3"
#  args: ['/bin/bash', 'script.sh']

## Deploy container image to GKE
- id: deployment
  name: "gcr.io/cloud-builders/gke-deploy"
  entrypoint: "bash"
  args:
    - "-c"
    - if ../gke-deploy run --filename=resource.yml --location=us-west1-a --cluster="gke-e2e-demo" ; then echo "success" > /workspace/deployment-status.txt ; else echo "fail" > /workspace/deployment-status.txt; fi
  #waitFor: ['whitelist']

## Delete the node IP from the control plane endpoint whitelist
#- id: whitelist_removal
#  name: "gcr.io/andres-testing/mybuilder:0.3"
#  args: ['/bin/bash', 'removeIP.sh']
#  waitFor: ['whitelist', 'deployment']

- id: deployment_result
  name: "gcr.io/andres-testing/mybuilder:0.3"
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [[ $(< /workspace/deployment-status.txt) == "fail" ]]; then
        echo "deployment step failed, please check that step for further details"
        exit 1
      else
        echo "the deployment step was successfully"
        exit 0
      fi
 # waitFor: ['whitelist', 'deployment', 'whitelist_removal']
