steps:
# Build container image 
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/andres-testing/nginx:latest', '.' ]
# Push container image to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/andres-testing/nginx:latest']

#  Copy the container image to gcr - it also shows the image in the build resutls at the build logs
#images:
#- 'gcr.io/caylent-testing/nginx:1.0.2'

#decrypts the alz-sa service account key from repo
#- name: gcr.io/cloud-builders/gcloud
#  args:
#  - kms
#  - decrypt
#  - --ciphertext-file=alz-sa-key.json.enc
#  - --plaintext-file=alz-sa-key.json
#  - --location=us-east1
#  - --keyring=caylent-testing-key-ring
#  - --key=caylent-testing-key
#  - --project=caylent-testing

# Getting the node public IP.
- name: "gcr.io/andres-testing/mybuilder"
  args: ['/bin/bash', 'script.sh']

# Edit the whitelist
#- name: "gcr.io/cloud-builders/gcloud"
  #args: ["container", "clusters", "describe", "gke-e2e-demo", "--region", "us-west1-a", "--impersonate-service-account=gke-custom@andres-testing.iam.gserviceaccount.com"]
  #args: ["container", "clusters", "list", "--region", "us-west1-a", "--impersonate-service-account=gke-custom@andres-testing.iam.gserviceaccount.com"]

#- name: google/cloud-sdk:latest
- name: "gcr.io/andres-testing/cloud-sdk"
  args: ["gcloud", "container", "clusters", "list", "--region", "us-west1-a", "--impersonate-service-account=gke-custom@andres-testing.iam.gserviceaccount.com"]
  args: ["cat", "/workspace/IP.txt"]
  args: ["cloud", "container", "clusters", "update", "gke-e2e-demo", "--enable-master-authorized-networks", "--master-authorized-networks", "3.3.3.3/32", "--region", "us-west1-a", "--impersonate-service-account=gke-custom@andres-testing.iam.gserviceaccount.com"]

#gcloud container clusters describe gke-e2e-demo --region us-west1-a --impersonate-service-account=gke-custom@andres-testing.iam.gserviceaccount.com
#gcloud container clusters update gke-e2e-demo --enable-master-authorized-networks --master-authorized-networks $PUBLIC_IP/32 --region us-west1-a --impersonate-service-account=gke-custom@andres-testing.iam.gserviceaccount.com


# deploy container image to GKE
#- name: "gcr.io/cloud-builders/gke-deploy"
#  args:
#  - run
#  - --filename=resource.yml
#  - --location=us-west1-1
#  - --cluster=gke-e2e-demo