bases:
- ../../base
# resources:
# - ../../base
# namePrefix: stg-
# namespace: stg




resources:
# - /Users/andreslz/repos/no-clients/basic-app/base
#- ../../base
- namespace.yaml

namePrefix: stg-
namespace: stg-namespace


# commonLabels:
#   variant: test
#   app: test-app

# patchesStrategicMerge:
# - secret.yaml
# - configmap.yaml